### ISSUE TITLE
zero stac items returned from Azure

### ISSUE THREAD

**Issue by rsignell-usgs** [TomAugspurger/stac-dask-discussion#1]
I tried running the summary.ipynb notebook, and this used to return 10, but now returns 0:
```
import requests

stac_items = requests.get(
    url="https://pct-pqe-staging.westeurope.cloudapp.azure.com/stac/v1/collections/usda-naip/items"
).json()["features"]
len(stac_items)
```
Would there be a better request to make now?

**Comment by TomAugspurger** [comment]
Yeah, I think `usda-naip` was changed to `naip` as part of a change for internal consistency. So `https://pct-pqe-staging.westeurope.cloudapp.azure.com/stac/v1/collections/naip/items` would be the URL to use.

A couple FYIs

- Our staging / production endpoints will be coming online over the next couple weeks, and `pct-pqe-staging.westeurope.cloudapp.azure.com` will be going away / falling out of date eventually.
- A couple endpoints that might be helpful:
  * /docs: https://pct-pqe-staging.westeurope.cloudapp.azure.com/stac/v1/docs, Let's you explore the API
  * /collections: https://pct-pqe-staging.westeurope.cloudapp.azure.com/stac/v1/collections, lists all the collections we have.

**Comment by TomAugspurger** [comment]
That raises an interesting point though, I'm surprised that `https://pct-pqe-staging.westeurope.cloudapp.azure.com/stac/v1/collections/not-a-collection/items` doesn't raise an exception. I don't know if that's intentional or not. I can check in the https://github.com/stac-utils/stac-fastapi repo.

**Comment by rsignell-usgs** [comment]
Indeed, using `url='https://pct-pqe-staging.westeurope.cloudapp.azure.com/stac/v1/collections/naip/items'` did the trick, getting 10 records again.
